Adhoc livestock analysis
databrew/bohemia pull request #100
Opened 2021-06-26 03:56 UTC by Sefadzi

Adhoc livestock analysis output files

2021-06-28 03:28 UTC, joebrew requested changes
@Sefadzi Please remove the csv file (and don't commit csv files in the future)

2021-06-28 03:29 UTC, joebrew commented
@Sefadzi Instead of committing csv files, please instead write documentation explaining where to get them and save them (but never put data in github)

2021-06-28 03:30 UTC, joebrew commented on analyses/adhoc_livestock_analysis/adhoc_livestock.Rmd
> +```{r}
The provenance of these files should be explained either (a) via comments or (b) in a separate README document so that someone can reproduce your code (ie, get the same data the same way you did, even if git-ignored)

2021-06-28 23:12 UTC, Sefadzi commented
> @Sefadzi Instead of committing csv files, please instead write documentation explaining where to get them and save them (but never put data in github)

@joebrew Done.

2021-06-28 23:13 UTC, Sefadzi commented
> @Sefadzi Please remove the csv file (and don't commit csv files in the future)

@joebrew file removed

2021-06-28 23:14 UTC, Sefadzi commented
> @Sefadzi Instead of committing csv files, please instead write documentation explaining where to get them and save them (but never put data in github)

@joebrew Noted

2021-06-29 21:25 UTC, joebrew commented on analyses/adhoc_livestock_analysis/adhoc_livestock.Rmd
> +knitr::opts_knit$set(root.dir = '/tmp')
Why in /tmp (just out of curiosity)?

2021-06-29 21:26 UTC, joebrew approved these changes
Looking good, @Sefadzi . Down to merge.

2021-06-30 20:52 UTC, joebrew commented
@Sefadzi Please go ahead and merge (and then move trello card to "done" as well)

2021-07-01 10:14 UTC, Sefadzi commented on analyses/adhoc_livestock_analysis/adhoc_livestock.Rmd
> +knitr::opts_knit$set(root.dir = '/tmp')
This ensures that you don't have to set working directory anytime you are running the notebook. You only put the data in the same directory as the notebook and run the code chunks.

2021-07-01 10:22 UTC, merged