Initial Commit
databrew/bohemia pull request #107
Opened 2021-07-29 14:59 UTC by Sefadzi

2021-07-31 07:26 UTC, AKostiv8 commented on scripts/ento/A4 Dashboard/app.R
> +get_entoa3_data = function(){
We are working in only one environment here no need to use `=` instead of general `<-`

2021-07-31 07:26 UTC, AKostiv8 commented on scripts/ento/A4 Dashboard/app.R
> +  require(dplyr)
the pack already declared on line 6

2021-07-31 07:27 UTC, AKostiv8 commented on scripts/ento/A4 Dashboard/app.R
> +  require(readr)
the pack already declared on line 5

2021-07-31 07:29 UTC, AKostiv8 commented on scripts/ento/A4 Dashboard/app.R
> +Species_Complex = as.factor(c("gambaie","Other"))
env?

2021-07-31 07:29 UTC, AKostiv8 commented on scripts/ento/A4 Dashboard/app.R
> +Parity_Status = as.factor(c("NP","P"))
env?

2021-07-31 08:47 UTC, AKostiv8 requested changes
I have found out that you can input any values you want instead of using select input available options, also, the app breaks when you put characters instead of numbers into the fields. Check the screencast https://drive.google.com/file/d/1MT97ndfEYdzvOWGWn7UhDQqT2CPuxcbo/view?usp=sharing, please

To fix: 

- [ ] dropdown selection
- [ ] numeric validation

BTW, I am not sure about using `=` instead of `<-` as we have only one environment, review it, please. 

Recommendation (optional): put the text ("The data is loading...") for example while you are waiting for the data is loading.

2021-08-02 12:11 UTC, Sefadzi commented on scripts/ento/A4 Dashboard/app.R
> +get_entoa3_data = function(){
Okay

2021-08-02 12:11 UTC, Sefadzi commented on scripts/ento/A4 Dashboard/app.R
> +  require(dplyr)
Okay

2021-08-03 18:55 UTC, AKostiv8 approved these changes

2021-08-03 18:55 UTC, AKostiv8 approved these changes

2021-08-13 20:27 UTC, katekimani approved these changes

2021-08-13 21:28 UTC, closed without merging