Add schema for postgres database.
databrew/bohemia pull request #11
Opened 2020-09-30 13:28 UTC by katekimani

**What PR does**
- Adds a file with the SQL commands to create tables for the `bohemia` database.
- Adds pseudocode to the kate_example.R file for the filtering existing instanceIDs from the fetch function and saving of retrieved data to DB.

2020-09-30 14:12 UTC, joebrew commented on misc/kate_example.R
> +con <- dbConnect(drv, dbname='bohemia', host='localhost', port=5432, user='bohem_app', password='riscrazy')
When running this, I get the following error:
```
Error in postgresqlNewConnection(drv, ...) : 
  RS-DBI driver: (could not connect bohem_app@localhost:5432 on dbname "bohemia": FATAL:  password authentication failed for user "bohem_app"
FATAL:  password authentication failed for user "bohem_app"
```

I'm guessing that this is because you created a "bohem_app" user at some point, correct? But I don't see this creation anywhere in the code / workflow...

2020-09-30 14:16 UTC, joebrew commented on misc/kate_example.R
> +con <- dbConnect(drv, dbname='bohemia', host='localhost', port=5432, user='bohem_app', password='riscrazy')
If I run with no authentication like this it works:
```
con <- dbConnect(drv, dbname='bohemia'
```

2020-09-30 14:26 UTC, katekimani commented on misc/kate_example.R
> +con <- dbConnect(drv, dbname='bohemia', host='localhost', port=5432, user='bohem_app', password='riscrazy')
That is correct, I cleaned up to be bohemia in the SQL just before push. Will fix this.

2020-09-30 14:37 UTC, joebrew commented on misc/kate_example.R
> +con <- dbConnect(drv, dbname='bohemia', host='localhost', port=5432, user='bohem_app', password='riscrazy')
It looks like maybe this should be `bohemia_app`, not `bohem_app`...

2020-09-30 14:44 UTC, joebrew requested changes
@katekimani back to you

2020-09-30 14:44 UTC, joebrew commented on misc/bohemia_db_schema.sql
> +-- NOTE switch to the bohemia database before proceeding with the following queries execution.
Can you add the command line code that should be run here to connect?
If I run `psql bohemia`, for example, it connects me (but as the current user).
If I try the following `psql -d bohemia -U bohemia_app -W` and then put it in the password, I get:
```
psql: FATAL:  Peer authentication failed for user "bohemia_app"
```

2020-09-30 14:44 UTC, joebrew commented on misc/kate_example.R
> +# Save the data to the DB
I haven't reviewed this part yet. First want to get clarity on the other section...

2020-09-30 16:12 UTC, joebrew commented on misc/bohemia_db_schema.sql
> +
Can you please add this to the documentation? This was the only way I was able to connect, authenticated...
```
export PGPASSWORD='riscrazy'; psql -h 'localhost' -U 'bohemia_app' -d 'bohemia'
```

2020-09-30 16:22 UTC, joebrew commented on misc/kate_example.R
> +existing_uuids <- dbGetQuery(con, 'SELECT instance_id FROM minicensus_main')
when you pass this object to the function below, it expects this to be a vector. But if this is empty, it returns a dataframe. So, please add the following code:
```
if(nrow(existing_uuids)< 0){ existing_uuids <- c()} else {existing_uuids <- existing_uuids$instance_id}

2020-09-30 16:23 UTC, joebrew requested changes
@katekimani Great work, minor comments. Back to you.

2020-10-01 05:13 UTC, katekimani commented on misc/bohemia_db_schema.sql
> +
Done

2020-10-01 05:14 UTC, katekimani commented on misc/kate_example.R
> +existing_uuids <- dbGetQuery(con, 'SELECT instance_id FROM minicensus_main')
Done

2020-10-01 06:59 UTC, joebrew approved these changes

2020-10-01 06:59 UTC, merged