Add cron job script for data updates
databrew/bohemia pull request #12
Opened 2020-10-05 13:40 UTC by katekimani

**What PR does**
- Adds a script to be executed by the crontab.
- Adds instructions to the guide on how to set the crontab on the EC2 instance.

2020-10-05 15:02 UTC, joebrew requested changes
@katekimani Looking good so far. A bit confused about the Rscript section (ie, how to reference correctly in the shebang, etc.). Can you ssh into the instance at at ubuntu@bohemia.systems and see if you can get this set up?

2020-10-05 17:12 UTC, joebrew commented on scripts/run_odk_get_data_cron.sh
> +${ROOT_FOLDER_PATH}/scripts/update_database.R
I think this needs some modification. Not exactly sure how (ie, how to run the script via command line: https://stackoverflow.com/questions/18306362/run-r-script-from-command-line). If you can figure it out, go for it; if not, happy to take over. Just let me know

2020-10-05 17:38 UTC, katekimani commented on scripts/run_odk_get_data_cron.sh
> +${ROOT_FOLDER_PATH}/scripts/update_database.R
I used the option of adding the `#!/usr/bin/RScript` to the R code to make this work.

2020-10-06 10:18 UTC, katekimani commented on scripts/run_odk_get_data_cron.sh
> +ROOT_FOLDER_PATH=/bohemia # TODO Update this to real path
@joebrew Confirmed the cron works correctly on the server.
```
Oct  6 10:15:01 ip-10-0-0-159 CRON[19971]: (root) CMD (sh /home/ubuntu/Documents/bohemia/scripts/run_odk_get_data_cron.sh)
Oct  6 10:15:01 ip-10-0-0-159 CRON[19972]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Oct  6 10:15:01 ip-10-0-0-159 CRON[19973]: (ubuntu) CMD (sh /home/ubuntu/Documents/bohemia/scripts/run_odk_get_data_cron.sh)
Oct  6 10:15:01 ip-10-0-0-159 CRON[19969]: (CRON) info (No MTA installed, discarding output)
Oct  6 10:15:01 ip-10-0-0-159 CRON[19970]: (CRON) info (No MTA installed, discarding output)
```

2020-10-06 10:34 UTC, joebrew approved these changes

2020-10-06 12:06 UTC, merged