added s3 loading
databrew/bohemia pull request #129
Opened 2021-09-30 11:35 UTC by Sefadzi

2021-09-30 16:21 UTC, katekimani requested changes
Please see comments inline. Also, would you deploy the new changes to https://sefadzi.shinyapps.io/entodashboard/ for me to test before we deploy prod.

Also, the readme on how to deploy, is this updated?

2021-09-30 16:21 UTC, katekimani commented on scripts/ento/ento_storage/R/app_server.R
> +    browser()
Debug feature needs clean up

2021-09-30 16:21 UTC, katekimani commented on scripts/ento/ento_storage/R/app_server.R
> +  #   hh_rv$df = isolate({
If the dashboard report has been moved ok, please clean up this commented out code.

2021-09-30 16:21 UTC, katekimani commented on scripts/ento/ento_storage/R/fct_A3storage.R
> +      dplyr::select_at(dplyr::vars(contains("how_many_stored")))%>%
Delete the L35 and L36 this is duplicating

2021-09-30 16:21 UTC, katekimani commented on scripts/ento/ento_storage/R/fct_C3storage.R
> +      "Cluster" = character(),
Why the change to cluster here? I believe the user review done approved the page with `HH ID`

2021-09-30 16:21 UTC, katekimani commented on scripts/ento/ento_storage/R/fct_C4_preprocess.R
> +                  "Collection location",
👍

2021-09-30 16:21 UTC, katekimani commented on scripts/ento/ento_storage/R/fct_getEntoDataC4.R
> +                          "Sample tube ID and link to QR code",
👍

2021-10-01 17:54 UTC, Sefadzi commented on scripts/ento/ento_storage/R/app_server.R
> +    browser()
alright

2021-10-04 18:07 UTC, katekimani requested changes
@Sefadzi  What is the reason for the `forms/*` in the PR? I am unclear as to how they ended up with changes on your branch, maybe update your branch with latest master changes?

2021-10-04 18:59 UTC, merged