livestock screening
databrew/bohemia pull request #130
Opened 2021-09-30 16:53 UTC by AKostiv8

2021-10-03 17:43 UTC, katekimani requested changes
Looks good for the livestock screening. Was expecting the data collection tool parts as well though.

Format changes requested inline

2021-10-03 17:43 UTC, katekimani commented on scripts/ento/ento_reports/app.R
> +  # })
Please clean up the commented out code.

2021-10-03 21:05 UTC, AKostiv8 commented on scripts/ento/ento_reports/app.R
> +  # })
@katekimani Data collection in progress. Requested changes are done.

2021-10-03 21:06 UTC, AKostiv8 commented
@katekimani Check again, please. I have integrated the questionnaires part to the app

2021-10-04 16:03 UTC, katekimani requested changes
Few calculations and alerts missing in the livestock

2021-10-04 16:13 UTC, AKostiv8 commented on scripts/ento/ento_reports/pages/mod_questionnaires.R
> +                      le_no_followup_gr = sum(.$le_no_followup_gr, na.rm = TRUE),
@katekimani I know, that the alert is missed - I separated it into another task yesterday ( https://trello.com/c/KXeXdQsG/345-connect-alert-to-questionnaires-part-communication-between-modules ) It is better to make after all modules are created as it requires "communication" between. modules

2021-10-04 18:00 UTC, merged