POC code for encrypting names
databrew/bohemia pull request #29
Opened 2020-11-09 01:16 UTC by katekimani

**What PR does**
- Adds POC code for R functions to handle the encrypt/decrypt of private data.

**Reference for package**
[PKI](https://www.rdocumentation.org/packages/PKI/versions/0.1-7/topics/PKI.crypt)

2020-11-12 23:19 UTC, katekimani commented on rpackage/bohemia/build_package.R
> +  usethis::use_package('PKI')
@joebrew Am unsure as to how the new packages are introduced, added this here however do let me know what is the correct 'build' process for a new function to be part of the package.

2020-11-13 13:06 UTC, joebrew requested changes
@katekimani Great work. Requested a few changes in line (and a few minor questions). Back to you

2020-11-13 13:06 UTC, joebrew commented on rpackage/bohemia/R/decrypt_private_data.R
> +decrypt_private_data <- function(data, keyfile){
did you need help with this still, or did you confirm that this works?

2020-11-13 13:06 UTC, joebrew commented on rpackage/bohemia/R/encrypt_private_data.R
> +encrypt_private_data <- function(data, keyfile){
is the expectation that the same pem file will be used both to encrypt and decrypt? we should have one file (ours) which is capable of encrypting, but not decrypting...

2020-11-13 13:06 UTC, joebrew commented on rpackage/bohemia/R/format_minicensus.R
> +  people_part$first_name <- encrypt_private_data(data = people_part$first_name, keyfile = keyfile)
This looks good. However, the same kind of change needs to be implemented in:
`format_va`
`format_enumerations`
(names also show up there)

Also, these functions (`format_...`) shoud take an argument for the `keyfile` path, rather than having it hard-coded into the internals of the functions (so that these functions can be called from any directory)...

2020-11-13 13:06 UTC, joebrew commented on rpackage/bohemia/build_package.R
> +  usethis::use_package('PKI')
perfect

2020-11-13 13:07 UTC, katekimani commented on rpackage/bohemia/R/decrypt_private_data.R
> +decrypt_private_data <- function(data, keyfile){
I confirmed it works. Won't hurt to get confirmation though.

2020-11-13 13:07 UTC, katekimani commented on rpackage/bohemia/R/encrypt_private_data.R
> +encrypt_private_data <- function(data, keyfile){
No. The generator function is creating 2 files. One public pem for encrypting and the private pem for decrypting

2020-11-16 22:31 UTC, merged