added queries
databrew/bohemia pull request #33
Opened 2020-11-11 02:27 UTC by xingcbrew

@joebrew, I've added 3 rows to `clean_database_fixes.py` for you to review. They were new queries (ie I couldn't copy/paste from previous rows), so I had to guess at how to write them. The first two rows share one correction id, but it looked like 2 changes were needed based on the response and I didn't know if I could write them in one query.

2020-11-11 05:17 UTC, joebrew commented on scripts/clean_database_fixes.py
> +implement(id = 'strange_hh_code_00f5b8ba-739c-428d-ae19-27f2be92044e', query = "UPDATE clean_minicensus_main SET hh_hamlet_code='DEO' WHERE instance_id='00f5b8ba-739c-428d-ae19-27f2be92044e'")
@xingcbrew a change to the hamlet code can have a lot of downstream changes (ie, it's a pretty major change). That is, it effects:

*clean_minicensus_main*
-`hh_hamlet_code`
-`hh_hamlet`
-`hh_village`
-`hh_id`

*clean_minicensus_people*
-`pid`
`permid`

So, for each of these kinds of changes, you should first:
1. Have a look at the data for the `instance_id` in question
2. Make changes to any "downstream" effected variables.


In the case of instance_id `00f5b8ba-739c-428d-ae19-27f2be92044e`, it looks like the people for that household were correctly given IDs (`DEO-`). So, in this particular case, you don't have to make any changes to the `people` table.

However, it looks like the variables in `clean_minicensus_main` where not correct:
-`hh_hamlet_code`
-`hh_hamlet`
-`hh_village`
(`hh_id` was correct)

Therefore, the `query` part of your line should be longer. The following:

implement(id = 'strange_hh_code_00f5b8ba-739c-428d-ae19-27f2be92044e', query = "UPDATE clean_minicensus_main SET hh_hamlet_code='DEO', hh_village='Marruma', hh_hamlet='4 de Outubro' WHERE instance_id='00f5b8ba-739c-428d-ae19-27f2be92044e'")

(Note that I had to retrieve the hamlet and village name from the locations hierarchy: https://docs.google.com/spreadsheets/d/1hQWeHHmDMfojs5gjnCnPqhBhiOeqKWG32xzLQgj5iBY/edit#gid=1134589765)

2020-11-11 05:18 UTC, joebrew commented on scripts/clean_database_fixes.py
> +implement(id = 'strange_hh_code_00f5b8ba-739c-428d-ae19-27f2be92044e', query = "UPDATE clean_minicensus_main SET hh_hamlet='4 de Outubro' WHERE instance_id='00f5b8ba-739c-428d-ae19-27f2be92044e'")
The `id` of the anomaly here is the same as the previous one. Each anomaly should be resolved y only one `implement` call. Therefore, the changing of the `hh_hamlet` value (what you've done here) should instead be done above, and this line should be removed.

2020-11-11 05:20 UTC, joebrew commented on scripts/clean_database_fixes.py
> +implement(id = 'strange_wid_enumerations_2939b05a-3bbe-4c1b-81fe-6eac54d47dc9', query = "UPDATE clean_enumerations SET wid='427' WHERE instance_id='2939b05a-3bbe-4c1b-81fe-6eac54d47dc9'")
The above is good.

2020-11-11 05:20 UTC, joebrew requested changes
@xingcbrew Added some comments. Back to you.

2020-11-12 02:06 UTC, xingcbrew commented
@joebrew I've updated the correction code based on your comments and completed a few more rows of corrections.

2020-11-12 09:39 UTC, joebrew commented on scripts/clean_database_fixes.py
> +implement(id = 'strange_hh_code_00f5b8ba-739c-428d-ae19-27f2be92044e', query = "UPDATE clean_minicensus_main SET hh_hamlet_code='DEO', hh_village='Marruma', hh_hamlet='4 de Outubro' WHERE instance_id
@xingcbrew Have you confirmed that for all of these `strange_hh_code_` anomalies the data in the `people` table is correct? That is, in many of these, you are making changes only to the `minicensus_main` table, but no changes to `mini_census_people`. If the hamlet code was incorrect, I would expect that both the `pid` and `permid` fields of the `people` table are also incorrect...

2020-11-12 09:39 UTC, joebrew commented on scripts/clean_database_fixes.py
> +    "UPDATE clean_minicensus_people SET pid='DEO-033-001' WHERE num='1' and instance_id='287b28f8-c6ba-4b4e-bd6f-b6778a729d93'";
Changes should be made both to `pid` and `permid` (they're identical, but both need to be updated...)

2020-11-12 09:40 UTC, joebrew commented on scripts/clean_database_fixes.py
> +implement(id = 'strange_hh_code_2c54e783-2281-429f-9896-060261a148db', query = "UPDATE clean_minicensus_main SET hh_hamlet_code='MIF', hh_village='Marruma, hh_hamlet='Mifarinha' WHERE instance_id='2c
Same question for the next 10 lines or so. Do we need to update more than just the hamlet code in the `clean_minicensus_main` table? What about the `pid` and `permid` fields in the `clean_minicensus_people` table with the same instance id?

2020-11-12 09:41 UTC, joebrew requested changes
@xingcbrew Back to you

2020-11-12 14:30 UTC, xingcbrew commented on scripts/clean_database_fixes.py
> +    "UPDATE clean_minicensus_people SET pid='DEO-033-001' WHERE num='1' and instance_id='287b28f8-c6ba-4b4e-bd6f-b6778a729d93'";
@joebrew Right, I've corrected this now. Thanks!

2020-11-12 15:00 UTC, joebrew commented
@xingcbrew As discussed, please:

1. Add comment lines (beginning with #) to indicate that a seemingly incomplete fix is actually complete (ie, weird hamlet codes which get changed, but no changes made to the members of the household)

2. Add a `who = 'Xing Brew'` argument to all of the lines you wrote.

2020-11-12 20:06 UTC, joebrew commented on scripts/clean_database_fixes.py
> +implement(id = 'strange_hh_code_2624afc1-f262-4bda-b20f-34176ed1c13b', query = "UPDATE clean_minicensus_main SET hh_hamlet_code='MIF', hh_village='Marruma, hh_hamlet='Mifarinha' WHERE instance_id='26
There is a missing ' after the word `Marruma`, which causes this to fail.

2020-11-12 20:07 UTC, joebrew commented on scripts/clean_database_fixes.py
> +implement(id = 'strange_hh_code_287b28f8-c6ba-4b4e-bd6f-b6778a729d93', query = "UPDATE clean_minicensus_main SET hh_hamlet_code='DEO', hh_village='Marruma, hh_hamlet='4 de Outubro', hh_id='DEO-033' W
Another missing '

2020-11-12 20:09 UTC, joebrew commented on scripts/clean_database_fixes.py
> +    "UPDATE clean_minicensus_people SET pid='DEO-033-001', permid='DEO-033-001' WHERE num='1' and instance_id='287b28f8-c6ba-4b4e-bd6f-b6778a729d93'";
For these multiple statements, EVERYTHING needs to go between the ".

What you've done is to make multiple statements wrapped in "", separated by semicolons. That is, you've done:
"statement a"; "statement b"; "statement c";

Instead it needs to be "statement a; statement b; statement c"

2020-11-12 20:09 UTC, joebrew commented on scripts/clean_database_fixes.py
> +implement(id = 'strange_hh_code_2c54e783-2281-429f-9896-060261a148db', query = "UPDATE clean_minicensus_main SET hh_hamlet_code='MIF', hh_village='Marruma, hh_hamlet='Mifarinha' WHERE instance_id='2c
Lots more of these missing ' after Marruma. Check quotations on all strings...

2020-11-12 20:12 UTC, joebrew reviewed
@xingcbrew A few comments in line. Back to you...

2020-11-16 11:55 UTC, joebrew approved these changes
@xingcbrew Looks good. I'm going to go ahead and merge.

2020-11-16 11:55 UTC, merged